[package]
name = "app"
version = "0.1.0"
edition.workspace = true

[dependencies]
cranelift = "0.126.0"
cranelift-codegen = { version = "0.126.0", features = ["x86"] }
cranelift-module = "0.126.0"
cranelift-object = "0.126.0"

[lints]
workspace = true
