[package]
name = "app"
version = "0.1.0"
edition.workspace = true

[dependencies]
cranelift = "0.128.3"
cranelift-codegen = { version = "0.128.0", features = ["x86"] }
cranelift-module = "0.128.0"
cranelift-object = "0.128.3"

[lints]
workspace = true
