[package]
name = "app"
version = "0.1.0"
edition.workspace = true

[dependencies]
cranelift = "0.125.4"
cranelift-codegen = { version = "0.125.1", features = ["x86"] }
cranelift-module = "0.125.1"
cranelift-object = "0.125.4"

[lints]
workspace = true
