[project]
name = "til"
version = "0.1.0"
description = "Today I learned"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[tool.uv.workspace]
members = [
    "stak-code-analysis",
    "python-property-set",
]

[dependency-groups]
dev = [
    "pyrefly>=0.46.3",
]
