[project]
name = "stak-code-analysis"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
  "matplotlib>=3.10.8",
  "numpy>=2.4.0",
  "polars>=1.36.1",
  "pyarrow>=22.0.0",
  "seaborn>=0.13.2",
]
