[package]
name = "dag-encoder"
description = "DAG encoder and decoder"
version = "0.1.0"
edition.workspace = true

[features]
alloc = []

[dependencies]
derivative = "2.2.0"

[dev-dependencies]
insta = "1.44.1"
pretty_assertions = "1.4.1"

[lints]
workspace = true
